# Generated by Django 3.2.13 on 2023-06-05 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20230605_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'verbose_name': 'Категория статей', 'verbose_name_plural': 'Категории статей'},
        ),
    ]
