# Generated by Django 3.2.13 on 2023-06-05 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_articlecategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arhivcategory',
            options={'verbose_name': 'Архив по месяцам', 'verbose_name_plural': 'Архив по месяцам'},
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статьи', 'verbose_name_plural': 'Статьи'},
        ),
    ]
