# Generated by Django 3.2.13 on 2023-06-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20230605_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True)),
                ('title_image', models.ImageField(upload_to='articles_images')),
                ('logo_image', models.ImageField(upload_to='articles_images')),
                ('title_logo_one', models.CharField(max_length=126, unique=True)),
                ('title_logo_two', models.CharField(max_length=126, unique=True)),
                ('login_text_one', models.CharField(max_length=256, unique=True)),
                ('login_text_two', models.CharField(max_length=256, unique=True)),
                ('strelka_image', models.ImageField(upload_to='articles_images')),
                ('slider_text_one', models.CharField(max_length=256, unique=True)),
                ('slider_button_one', models.CharField(max_length=256, unique=True)),
                ('slider_image_one', models.ImageField(upload_to='articles_images')),
                ('slider_text_two', models.CharField(max_length=256, unique=True)),
                ('slider_button_two', models.CharField(max_length=256, unique=True)),
                ('slider_image_two', models.ImageField(upload_to='articles_images')),
                ('info_title', models.CharField(max_length=256, unique=True)),
                ('info_description', models.TextField()),
                ('infoblock_card_image_one', models.ImageField(upload_to='articles_images')),
                ('infoblock_card_title_one', models.CharField(max_length=256, unique=True)),
                ('infoblock_card_description_one', models.TextField()),
                ('infoblock_card_image_two', models.ImageField(upload_to='articles_images')),
                ('infoblock_card_title_two', models.CharField(max_length=126, unique=True)),
                ('infoblock_card_description_two', models.TextField()),
                ('infoblock_card_image_three', models.ImageField(upload_to='articles_images')),
                ('infoblock_card_title_three', models.CharField(max_length=126, unique=True)),
                ('infoblock_card_description_three', models.TextField()),
                ('tools_title', models.CharField(max_length=256, unique=True)),
                ('tools_text', models.TextField()),
                ('tools_item_image_one', models.ImageField(upload_to='articles_images')),
                ('tools_item_title_one', models.CharField(max_length=256, unique=True)),
                ('tools_item_text_one', models.TextField()),
                ('tools_item_image_two', models.ImageField(upload_to='articles_images')),
                ('tools_item_title_two', models.CharField(max_length=256, unique=True)),
                ('tools_item_text_two', models.TextField()),
                ('tools_item_image_three', models.ImageField(upload_to='articles_images')),
                ('tools_item_title_three', models.CharField(max_length=256, unique=True)),
                ('tools_item_text_three', models.TextField()),
                ('footer_title', models.CharField(max_length=256, unique=True)),
            ],
        ),
    ]
