# Generated by Django 3.2.13 on 2023-06-09 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20230609_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, null=True)),
                ('info', models.TextField(null=True)),
                ('image_one', models.ImageField(upload_to='articles_images')),
                ('image_two', models.ImageField(upload_to='articles_images')),
                ('title_mini', models.CharField(max_length=128, null=True)),
                ('info_mini', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Контент для статей',
                'verbose_name_plural': 'Контент для статей',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='add',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.articleadd'),
        ),
    ]
