# Generated by Django 3.2.13 on 2023-06-09 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20230609_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='add',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.articleadd'),
        ),
    ]
