# Generated by Django 3.2.13 on 2023-06-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_article_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='add',
        ),
        migrations.AddField(
            model_name='article',
            name='image_one',
            field=models.ImageField(default='cris2.jpg', upload_to='articles_images'),
        ),
        migrations.AddField(
            model_name='article',
            name='image_two',
            field=models.ImageField(default='cris2.jpg', upload_to='articles_images'),
        ),
        migrations.AddField(
            model_name='article',
            name='info',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='info_mini',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_mini',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name='ArticleAdd',
        ),
    ]
