# Generated by Django 3.2.13 on 2023-06-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Страница About', 'verbose_name_plural': 'Страница About'},
        ),
        migrations.AddField(
            model_name='about',
            name='profile_more_text_two',
            field=models.CharField(default='О себе:', max_length=126, unique=True, verbose_name='Второй текст в профиле'),
        ),
        migrations.AlterField(
            model_name='about',
            name='profile_more_text',
            field=models.CharField(max_length=126, unique=True, verbose_name='Первый текст в профиле'),
        ),
    ]
