# Generated by Django 3.2.13 on 2023-06-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_exercisefive_exercisefo_exerciseone_exercisesix_exercisethree_exercisetwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='One',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_about', models.CharField(max_length=256, unique=True, verbose_name='Заголовок about')),
                ('title_image', models.ImageField(upload_to='articles_images', verbose_name='Изображение title')),
                ('logo_image', models.ImageField(upload_to='articles_images', verbose_name='Изображение логотипа')),
                ('header_logo_one', models.CharField(max_length=126, unique=True, verbose_name='Текст первой части логотипа')),
                ('header_logo_two', models.CharField(max_length=126, unique=True, verbose_name='Текст второй части логотипа')),
                ('about_title', models.CharField(max_length=126, unique=True, verbose_name='Текст первой вкладки меню')),
                ('about_title_two', models.CharField(max_length=126, unique=True, verbose_name='Текст второй вкладки меню')),
                ('about_title_three', models.CharField(max_length=126, unique=True, verbose_name='Текст третей вкладки меню')),
                ('burger_title', models.CharField(max_length=126, unique=True, verbose_name='Текст в бургер  меню')),
                ('about_images', models.CharField(max_length=126, unique=True, verbose_name='Главный текст в about_images')),
                ('about_images_title', models.CharField(max_length=126, unique=True, verbose_name='Втрой текст в about_images')),
                ('about_images_text', models.CharField(max_length=126, unique=True, verbose_name='Третий текст в about_images')),
                ('one_title', models.CharField(max_length=256, unique=True, verbose_name='Заголовок категорий')),
                ('one_title_one', models.CharField(max_length=256, unique=True, verbose_name='Текст первой категории')),
                ('one_title_two', models.CharField(max_length=256, unique=True, verbose_name='Текст второй категории')),
                ('one_title_three', models.CharField(max_length=256, unique=True, verbose_name='Текст третий категории')),
                ('one_title_fo', models.CharField(max_length=256, unique=True, verbose_name='Текст четвертой категории')),
                ('one_title_five', models.CharField(max_length=256, unique=True, verbose_name='Текст пятой категории')),
                ('one_title_six', models.CharField(max_length=256, unique=True, verbose_name='Текст шестой категории')),
                ('one_content_title', models.CharField(max_length=256, unique=True, verbose_name='Заголовок контекста первый')),
                ('one_content_text', models.TextField(max_length=456, unique=True, verbose_name='Текст первый контекста')),
                ('one_content_title_two', models.CharField(max_length=256, unique=True, verbose_name='Заголовок контекста второй')),
                ('one_content_text_two', models.TextField(max_length=456, unique=True, verbose_name='Текст второй контекста')),
                ('one_content_title_three', models.CharField(max_length=256, unique=True, verbose_name='Заголовок контекста третий')),
                ('one_content_text_three', models.TextField(max_length=456, unique=True, verbose_name='Текст третий контекста')),
                ('one_content_title_fo', models.CharField(max_length=256, unique=True, verbose_name='Заголовок контекста четвертый')),
                ('one_button', models.CharField(max_length=256, unique=True, verbose_name='Текст первой кнопки')),
                ('one_button_two', models.CharField(max_length=256, unique=True, verbose_name='Текст второй кнопки')),
                ('one_modal_title', models.CharField(max_length=256, unique=True, verbose_name='Заголовок модального окна')),
                ('one_image_one', models.ImageField(upload_to='articles_images', verbose_name='Первое изображение модального окна')),
                ('one_image_two', models.ImageField(upload_to='articles_images', verbose_name='Второе изображение модального окна')),
                ('one_image_three', models.ImageField(upload_to='articles_images', verbose_name='Третье изображение модального окна')),
                ('one_image_fo', models.ImageField(upload_to='articles_images', verbose_name='Четвертое изображение модального окна')),
                ('one_modal_title_min', models.CharField(max_length=256, unique=True, verbose_name='Второй заголовок модального окна')),
                ('one_modal_description', models.CharField(max_length=256, unique=True, verbose_name='Второое описание модального окна')),
            ],
            options={
                'verbose_name': 'Первая страница упражнений',
                'verbose_name_plural': 'Первая страница упражнений',
            },
        ),
        migrations.DeleteModel(
            name='ExerciseFive',
        ),
        migrations.DeleteModel(
            name='ExerciseFo',
        ),
        migrations.DeleteModel(
            name='ExerciseOne',
        ),
        migrations.DeleteModel(
            name='ExerciseSix',
        ),
        migrations.DeleteModel(
            name='ExerciseThree',
        ),
        migrations.DeleteModel(
            name='ExerciseTwo',
        ),
    ]
