# Generated by Django 3.2.13 on 2023-06-16 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_auto_20230616_1835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='One',
        ),
    ]
