# Generated by Django 3.2.13 on 2023-06-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_from_admin',
            field=models.BooleanField(default=False),
        ),
    ]
